name: Groups
main: groups.Groups
version: 0.1
description: Groups
author: Gu3rr1lla
database: false
commands:
  gcreate:
    description: Creates a Group
    usage: /gcreate <name>
  gdelete:
    description: Deletes a Group
    usage: /gdelete <name>
  glistall:
    description: Lists all Groups
    usage: /glistall
  gadd:
    description: Adds a member to a group
    usage: /gadd <group> <player> <type>
  gremove:
    description: Removes a member from a group
    usage: /gremove <group> <player>
  glistmembers:
    description: List all members of a group
    usage: /glistmembers <group>
  ginfo:
    description: Displays information about a group
    usage: /ginfo <group>
  gsetpassword:
    description: Set the password for a group
    usage: /gsetpassword <group> <password>
  gjoingroup:
    description: Join a group
    usage: /gjoingroup <group> <password>