name: Groups
main: groups.Groups
version: 0.1
description: Groups
author: Gu3rr1lla
database: false
commands:
  gcreate:
    description: Creates a Group
    usage: /gcreate <name>
  gdelete:
    description: Deletes a Group
    usage: /gdelete <name>